const LABELS_URL = process.env.LABELS_URL;
const LOCALISE_KEY = process.env.LOCALISE_KEY;
const DOMAIN_URL = process.env.NEXT_PUBLIC_DOMAIN_URL;
const COOKIES_DOMAIN = process.env.NEXT_PUBLIC_COOKIES_DOMAIN;
const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;
const GOOGLE_ENGINE_CX = process.env.NEXT_PUBLIC_GOOGLE_ENGINE_CX;
const API_URL = process.env.NEXT_PUBLIC_API_URL;
const API_KEY = process.env.NEXT_PUBLIC_API_KEY_CLOUDFLARE;

export {
  LABELS_URL,
  LOCALISE_KEY,
  DOMAIN_URL,
  COOKIES_DOMAIN,
  GOOGLE_API_KEY,
  GOOGLE_ENGINE_CX,
  API_URL,
  API_KEY,
};
