const LABELS_URL = process.env.LABELS_URL;
const LOCALISE_KEY = process.env.LOCALISE_KEY;
const DOMAIN_URL = process.env.NEXT_PUBLIC_DOMAIN_URL;
const COOKIES_DOMAIN = process.env.NEXT_PUBLIC_COOKIES_DOMAIN;

export { LABELS_URL, LOCALISE_KEY, DOMAIN_URL, COOKIES_DOMAIN };
