import "src/styles/globals.css";

import { getLanguage } from "src/services/server";

import type { Metadata } from "next";

type Props = Readonly<{ children: React.ReactNode }>;

const Body = "w-screen h-screen overflow-hidden";

export default function RootLayout({ children }: Props) {
  const language = getLanguage();

  return (
    <html lang={language}>
      <body className={Body}>{children}</body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
